### ISSUE TITLE
Release Testing Suite

### ISSUE THREAD

**Issue by jeremyw24** [PlaceOS/release#48]
Integrated/automated tests on release version.

Overarching Plan: https://docs.google.com/document/d/1FFUcNcLReh9y9PtQXkzrsgUPQiNUvdJQnfZqjkNEKRI/edit#

**Comment by kimburgess** [comment]
Grouping related tasks here that will form the overall suite and associated infra:

- [ ] [E2E functional tests](https://github.com/PlaceOS/PlaceOS/issues/7)
- [ ] [Verify API behaviour](https://github.com/PlaceOS/PlaceOS/issues/119)
- [ ] [Image analysis](https://github.com/PlaceOS/PlaceOS/issues/12)
- [ ] [Load testing](https://github.com/place-labs/product-team-bau/issues/7)
- [ ] [Enable release channels](https://github.com/PlaceOS/PlaceOS/issues/76)
